### ISSUE TITLE
improve: BankTeller should not create "BankSystem"

### ISSUE THREAD

**Issue by chifai** [shawan-w/Cpp_practice#5]
It's not reasonable for `BankTeller` to create `BankSystem`. Instead, `BankSystem` should only be "used" by `BankTeller`. As such, `BankSystem` should be built out of the scope of `BankTeller` (in current case: `BankEntry`). Then `BankSystem` is passed to `BankTeller` by reference for its use.

Objectives:
1. Build `BankSystem` in `BankEntry`
2. Pass `BankSystem` to `BankTeller` as reference. 
Tips: `BankTeller` without `BankSystem` is a useless object. The best approach is to pass `BankSystem` to `BankTeller` while at its instantiation stage (i.e. `BankTeller` constructor)

UML will become as following after changes.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/21029911/120094510-63752500-c153-11eb-92f6-90da8484e06b.png">

**Comment by shawan-w** [comment]
[Check this out](https://github.com/shawan-w/Cpp_practice/commit/ac39375f3af00b14f027c65aeeb8efa2c535fc65)

**Comment by chifai** [comment]
good job!
